[package]
name = "ructe"
version = "0.4.3-PRE"
authors = ["Rasmus Kaj <kaj@kth.se>"]
description = "Rust Compiled Templates, efficient type-safe web page templates."
documentation = "https://docs.rs/ructe"
repository = "https://github.com/kaj/ructe"
readme = "README.md"
keywords = ["web", "templating", "html"]
categories = ["template-engine", "web-programming"]
license = "MIT/Apache-2.0"

[features]
sass = ["rsass"]
mime02 = []
mime03 = []

[dependencies]
base64 = "^0.9.0"
itertools = "^0.7.8"
lazy_static = "1.0"
md5 = "^0.3"
nom = { version = "^4.0", features = ["verbose-errors"], default-features = false }

rsass = { version = "^0.9.0", optional = true }

[badges]
travis-ci = { repository = "kaj/ructe" }
maintenance = { status = "actively-developed" }
